apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlHeadless.name }}
  labels:
    app: {{ .Values.mysqlHeadless.labelApp }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mysqlHeadless.labelApp }}
  ports:
    - port: {{ .Values.mysqlHeadless.port }}
      targetPort: {{ .Values.mysqlHeadless.targetPort }}
      name: {{ .Values.mysqlHeadless.portName }}