apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.targetPort }}