apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingressresource.name}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.nginx.serverName }}
    secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.nginx.serverName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontendService.name }}
            port:
              number: {{ .Values.frontendService.port }}