imagePullSecret:
  name: regcred
  dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtb29wc2RldiIsInBhc3N3b3JkIjoibWVnb2hqOTg3MjAiLCJhdXRoIjoiYlc5dmNITmtaWFk2YldWbmIyaHFPVGczTWpBPSJ9fX0=


mysqlSecret:
  name: mysql-secrets
  rootPassword: c2VjcmV0
  user: bGFyYXZlbA==
  password: c2VjcmV0
  appKey: YmFzZTY0OnFOL1hYWm1yVXRZamRDTWdrZzl3bjZjTGJzWXcwUzFxMytnU2g4SmNoWnM9


configmaps:
  appConfigName: app-config
  nginxConfigName: nginx-config

app:
  name: "Library API"
  env: "production"
  debug: "false"
  url: "https://laravel.lib:32140"

database:
  connection: "mysql"
  port: "3306"
  name: "laravel"

nginx:
  serverName: "laravel.lib"
  backendService: "laravel-backend-service"


rbac:
  serviceAccountName: laravel-sa
  roleName: laravel-role
  roleBindingName: laravel-rolebinding